import React, { useState } from 'react';
import {
  Salad, Download, Calculator, Loader2, AlertTriangle, CheckCircle,
  UtensilsCrossed, ShoppingCart, Lightbulb, BarChart3, Clock, Sparkles,
  Apple, Dumbbell,
} from 'lucide-react';
import { API_BASE_URL } from '../config/constants';

const DietPlan = ({ language = 'english' }) => {
  const [formData, setFormData] = useState({
    age: '', weight: '', height: '', gender: '', dietaryPreference: 'balanced',
    healthConditions: '', activityLevel: 'moderate', goals: 'diabetes_prevention',
    allergies: '', typicalDay: '',
  });
  const [dietPlan, setDietPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const isTr = language === 'turkish';
  const t = isTr ? {
    badge: 'Yapay Zeka Beslenme', title: 'Diyet Planı', subtitle: 'Diyabet önleme ve yönetimi için kişiselleştirilmiş yapay zeka destekli öğün planları.',
    bodyMetrics: 'Vücut Ölçüleri', preferences: 'Tercihler', additionalInfo: 'Ek Bilgi',
    age: 'Yaş', weight: 'Kilo (kg)', height: 'Boy (cm)', gender: 'Cinsiyet', select: 'Seçin...',
    male: 'Erkek', female: 'Kadın', bmi: 'VKİ', dailyCalories: 'Günlük Kalori', goal: 'Hedef', kcalDay: 'kcal/gün',
    dietType: 'Diyet Tipi', activityLevel: 'Aktivite Seviyesi', goalLabel: 'Hedef',
    healthConditions: 'Sağlık Durumu', allergies: 'Alerjiler', dailyRoutine: 'Günlük Rutin',
    placeholders: { health: 'örn. yüksek tansiyon', allergies: 'örn. glüten', routine: 'örn. 07:00\'da kalk' },
    generate: 'Diyet Planı Oluştur', generating: 'Oluşturuluyor...', planGenerated: 'Plan oluşturuldu!',
    yourPlan: 'Diyet Planınız', generatedBy: 'Profilinize göre yapay zeka tarafından oluşturuldu',
    overview: 'Genel Bakış', dailyMeals: 'Günlük Öğünler', groceries: 'Alışveriş Listesi', importantNotes: 'Önemli Notlar',
    calories: 'Kalori', protein: 'Protein', carbs: 'Karbonhidrat', fat: 'Yağ',
    underweight: 'Zayıf', normal: 'Normal', overweight: 'Fazla Kilolu', obese: 'Obez',
    dietOptions: [{ value: 'balanced', label: 'Dengeli' }, { value: 'vegetarian', label: 'Vejetaryen' }, { value: 'non-vegetarian', label: 'Vejetaryen Değil' }, { value: 'vegan', label: 'Vegan' }, { value: 'mediterranean', label: 'Akdeniz' }, { value: 'low_carb', label: 'Düşük Karbonhidrat' }, { value: 'diabetic_friendly', label: 'Diyabet Dostu' }],
    activityOptions: [{ value: 'sedentary', label: 'Hareketsiz' }, { value: 'light', label: 'Hafif' }, { value: 'moderate', label: 'Orta' }, { value: 'active', label: 'Aktif' }, { value: 'very_active', label: 'Çok Aktif' }],
    goalOptions: [{ value: 'diabetes_prevention', label: 'Diyabet Önleme' }, { value: 'blood_sugar_control', label: 'Kan Şekeri Kontrolü' }, { value: 'weight_loss', label: 'Kilo Verme' }, { value: 'weight_gain', label: 'Kilo Alma' }, { value: 'maintenance', label: 'Koruma' }, { value: 'gestational_diabetes', label: 'Gestasyonel Diyabet' }],
    goalDisplay: { diabetes_prevention: 'Diyabet önleme', blood_sugar_control: 'Kan şekeri kontrolü', weight_loss: 'Kilo verme', weight_gain: 'Kilo alma', maintenance: 'Koruma', gestational_diabetes: 'Gestasyonel diyabet' },
  } : {
    badge: 'AI Nutrition', title: 'Diet Planner', subtitle: 'Personalized AI-generated meal plans for diabetes prevention and management.',
    bodyMetrics: 'Body Metrics', preferences: 'Preferences', additionalInfo: 'Additional Info',
    age: 'Age', weight: 'Weight (kg)', height: 'Height (cm)', gender: 'Gender', select: 'Select...',
    male: 'Male', female: 'Female', bmi: 'BMI', dailyCalories: 'Daily Calories', goal: 'Goal', kcalDay: 'kcal/day',
    dietType: 'Diet Type', activityLevel: 'Activity Level', goalLabel: 'Goal',
    healthConditions: 'Health Conditions', allergies: 'Allergies', dailyRoutine: 'Daily Routine',
    placeholders: { health: 'e.g., high BP', allergies: 'e.g., gluten', routine: 'e.g., wake 7AM' },
    generate: 'Generate Diet Plan', generating: 'Generating...', planGenerated: 'Plan generated!',
    yourPlan: 'Your Diet Plan', generatedBy: 'Generated by AI based on your profile',
    overview: 'Overview', dailyMeals: 'Daily Meals', groceries: 'Groceries', importantNotes: 'Important Notes',
    calories: 'Calories', protein: 'Protein', carbs: 'Carbs', fat: 'Fat',
    underweight: 'Underweight', normal: 'Normal', overweight: 'Overweight', obese: 'Obese',
    dietOptions: [{ value: 'balanced', label: 'Balanced' }, { value: 'vegetarian', label: 'Vegetarian' }, { value: 'non-vegetarian', label: 'Non-Vegetarian' }, { value: 'vegan', label: 'Vegan' }, { value: 'mediterranean', label: 'Mediterranean' }, { value: 'low_carb', label: 'Low Carb' }, { value: 'diabetic_friendly', label: 'Diabetic Friendly' }],
    activityOptions: [{ value: 'sedentary', label: 'Sedentary' }, { value: 'light', label: 'Light' }, { value: 'moderate', label: 'Moderate' }, { value: 'active', label: 'Active' }, { value: 'very_active', label: 'Very Active' }],
    goalOptions: [{ value: 'diabetes_prevention', label: 'Diabetes Prevention' }, { value: 'blood_sugar_control', label: 'Blood Sugar Control' }, { value: 'weight_loss', label: 'Weight Loss' }, { value: 'weight_gain', label: 'Weight Gain' }, { value: 'maintenance', label: 'Maintenance' }, { value: 'gestational_diabetes', label: 'Gestational Diabetes' }],
    goalDisplay: { diabetes_prevention: 'Diabetes prevention', blood_sugar_control: 'Blood sugar control', weight_loss: 'Weight loss', weight_gain: 'Weight gain', maintenance: 'Maintenance', gestational_diabetes: 'Gestational diabetes' },
  };

  const update = (f, v) => setFormData(p => ({ ...p, [f]: v }));

  const generateDietPlan = async () => {
    setLoading(true); setError(''); setSuccess('');
    try {
      const d = { ...formData }; delete d.bmi; delete d.bmi_category;
      const r = await fetch(`${API_BASE_URL}/api/v1/diet-plan/generate`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(d),
      });
      if (!r.ok) throw new Error((await r.json()).detail || 'Failed');
      setDietPlan(await r.json()); setSuccess(t.planGenerated);
    } catch (err) { setError(err.message); } finally { setLoading(false); }
  };

  const bmi = formData.weight && formData.height ? (formData.weight / ((formData.height / 100) ** 2)).toFixed(1) : null;
  const bmiCatKey = bmi ? (bmi < 18.5 ? 'underweight' : bmi <= 24.9 ? 'normal' : bmi <= 29.9 ? 'overweight' : 'obese') : '';
  const bmiCat = bmiCatKey ? t[bmiCatKey] : '';

  const calories = (() => {
    if (!formData.weight || !formData.height || !formData.age || !formData.gender || !formData.activityLevel) return null;
    const bmr = formData.gender === 'male'
      ? 88.362 + 13.397 * formData.weight + 4.799 * formData.height - 5.677 * formData.age
      : 447.593 + 9.247 * formData.weight + 3.098 * formData.height - 4.330 * formData.age;
    const mul = { sedentary: 1.2, light: 1.375, moderate: 1.55, active: 1.725, very_active: 1.9 };
    return Math.round(bmr * (mul[formData.activityLevel] || 1.55));
  })();

  const valid = formData.age && formData.weight && formData.height && formData.gender;

  const Input = ({ label, field, type = 'text', required, hint, ...rest }) => (
    <div>
      <label className="block text-sm font-semibold text-gray-300 mb-2">
        {label} {required && <span className="text-emerald-400">*</span>}
      </label>
      <input type={type} value={formData[field]} onChange={(e) => update(field, e.target.value)}
        className="input-field" {...rest} />
      {hint && <p className="text-[11px] text-gray-600 mt-1.5">{hint}</p>}
    </div>
  );

  const Select = ({ label, field, options, required }) => (
    <div>
      <label className="block text-sm font-semibold text-gray-300 mb-2">
        {label} {required && <span className="text-emerald-400">*</span>}
      </label>
      <select value={formData[field]} onChange={(e) => update(field, e.target.value)} className="select-field">
        <option value="">{t.select}</option>
        {options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
      </select>
    </div>
  );

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 pt-32 pb-16">
      {/* Header */}
      <div className="text-center mb-14 animate-fade-in-up">
        <div className="inline-flex items-center gap-2 bg-amber-500/10 border border-amber-500/20 rounded-full px-5 py-2 mb-5">
          <Sparkles className="w-4 h-4 text-amber-400" />
          <span className="text-[11px] font-extrabold text-amber-400 uppercase tracking-[0.15em]">{t.badge}</span>
        </div>
        <h1 className="text-4xl sm:text-5xl font-black text-white mb-3 tracking-tight">{t.title}</h1>
        <p className="text-gray-500 max-w-md mx-auto">{t.subtitle}</p>
      </div>

      {error && <div className="flex items-center gap-3 p-4 mb-8 rounded-xl bg-red-500/10 border border-red-500/20 text-red-300 text-sm animate-fade-in-up"><AlertTriangle className="w-5 h-5 shrink-0" />{error}</div>}
      {success && <div className="flex items-center gap-3 p-4 mb-8 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 text-sm animate-fade-in-up"><CheckCircle className="w-5 h-5 shrink-0" />{success}</div>}

      <div className="gradient-border animate-fade-in-up">
        <div className="card p-8 sm:p-10 rounded-[1.25rem]">
          {/* Section 1: Body Metrics */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-cyan-500/10 flex items-center justify-center">
                <Calculator className="w-5 h-5 text-cyan-400" />
              </div>
              <h2 className="text-lg font-bold text-white">{t.bodyMetrics}</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
              <Input label={t.age} field="age" type="number" required />
              <Input label={t.weight} field="weight" type="number" required />
              <Input label={t.height} field="height" type="number" required />
              <Select label={t.gender} field="gender" required options={[{ value: 'male', label: t.male }, { value: 'female', label: t.female }]} />
            </div>
          </div>

          {/* Live metrics */}
          {(bmi || calories) && (
            <div className="grid grid-cols-3 gap-4 mb-10">
              {bmi && (
                <div className="card p-4 text-center">
                  <p className="text-[10px] text-gray-500 uppercase tracking-[0.15em] font-bold mb-1">{t.bmi}</p>
                  <p className={`text-2xl font-black ${bmiCatKey === 'normal' ? 'text-emerald-400' : bmiCatKey === 'overweight' ? 'text-amber-400' : 'text-red-400'}`}>{bmi}</p>
                  <p className="text-[11px] text-gray-500 mt-0.5">{bmiCat}</p>
                </div>
              )}
              {calories && (
                <div className="card p-4 text-center">
                  <p className="text-[10px] text-gray-500 uppercase tracking-[0.15em] font-bold mb-1">{t.dailyCalories}</p>
                  <p className="text-2xl font-black text-cyan-400">{calories}</p>
                  <p className="text-[11px] text-gray-500 mt-0.5">{t.kcalDay}</p>
                </div>
              )}
              <div className="card p-4 text-center">
                <p className="text-[10px] text-gray-500 uppercase tracking-[0.15em] font-bold mb-1">{t.goal}</p>
                <p className="text-lg font-black text-violet-400">{t.goalDisplay[formData.goals] || formData.goals.replace(/_/g, ' ')}</p>
              </div>
            </div>
          )}

          {/* Section 2: Preferences */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center">
                <UtensilsCrossed className="w-5 h-5 text-amber-400" />
              </div>
              <h2 className="text-lg font-bold text-white">{t.preferences}</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
              <Select label={t.dietType} field="dietaryPreference" options={t.dietOptions} />
              <Select label={t.activityLevel} field="activityLevel" options={t.activityOptions} />
              <Select label={t.goalLabel} field="goals" options={t.goalOptions} />
            </div>
          </div>

          {/* Section 3: Additional Info */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-violet-500/10 flex items-center justify-center">
                <Lightbulb className="w-5 h-5 text-violet-400" />
              </div>
              <h2 className="text-lg font-bold text-white">{t.additionalInfo}</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
              <Input label={t.healthConditions} field="healthConditions" placeholder={t.placeholders.health} />
              <Input label={t.allergies} field="allergies" placeholder={t.placeholders.allergies} />
              <Input label={t.dailyRoutine} field="typicalDay" placeholder={t.placeholders.routine} />
            </div>
          </div>

          <div className="text-center">
            <button onClick={generateDietPlan} disabled={loading || !valid} className="btn-primary text-base px-10 py-4">
              {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <UtensilsCrossed className="w-5 h-5" />}
              {loading ? t.generating : t.generate}
            </button>
          </div>
        </div>
      </div>

      {/* Result */}
      {dietPlan && (
        <div className="gradient-border mt-10 animate-fade-in-up">
          <div className="card p-8 sm:p-10 rounded-[1.25rem]">
            <div className="flex items-center justify-between mb-10">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-500 to-cyan-500 flex items-center justify-center shadow-lg shadow-emerald-500/20">
                  <Salad className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h2 className="text-2xl font-black text-white">{t.yourPlan}</h2>
                  <p className="text-sm text-gray-500">{t.generatedBy}</p>
                </div>
              </div>
              <button className="btn-ghost text-xs"><Download className="w-4 h-4" /> PDF</button>
            </div>

            <div className="space-y-8">
              {dietPlan.overview && (
                <div>
                  <div className="flex items-center gap-2.5 mb-3"><BarChart3 className="w-5 h-5 text-emerald-400" /><h3 className="font-bold text-white">{t.overview}</h3></div>
                  <p className="text-sm text-gray-400 whitespace-pre-line leading-relaxed">{dietPlan.overview}</p>
                </div>
              )}
              {dietPlan.daily_plan && (
                <div>
                  <div className="flex items-center gap-2.5 mb-3"><UtensilsCrossed className="w-5 h-5 text-amber-400" /><h3 className="font-bold text-white">{t.dailyMeals}</h3></div>
                  <p className="text-sm text-gray-400 whitespace-pre-line leading-relaxed">{dietPlan.daily_plan}</p>
                </div>
              )}
              {dietPlan.grocery_list && (
                <div>
                  <div className="flex items-center gap-2.5 mb-3"><ShoppingCart className="w-5 h-5 text-cyan-400" /><h3 className="font-bold text-white">{t.groceries}</h3></div>
                  <p className="text-sm text-gray-400 whitespace-pre-line leading-relaxed">{dietPlan.grocery_list}</p>
                </div>
              )}
              {dietPlan.important_notes && (
                <div className="card p-5 bg-blue-500/[0.04] border-blue-500/10">
                  <div className="flex items-center gap-2.5 mb-2"><Lightbulb className="w-5 h-5 text-blue-400" /><h4 className="font-bold text-blue-300">{t.importantNotes}</h4></div>
                  <p className="text-sm text-blue-300/80 whitespace-pre-line leading-relaxed">{dietPlan.important_notes}</p>
                </div>
              )}
              {dietPlan.nutritional_info && (
                <div className="grid grid-cols-4 gap-3">
                  {[
                    { label: t.calories, value: dietPlan.nutritional_info.daily_calories, unit: 'kcal' },
                    { label: t.protein, value: dietPlan.nutritional_info.protein_grams, unit: 'g' },
                    { label: t.carbs, value: dietPlan.nutritional_info.carbs_grams, unit: 'g' },
                    { label: t.fat, value: dietPlan.nutritional_info.fat_grams, unit: 'g' },
                  ].map((n, i) => (
                    <div key={i} className="card p-4 text-center">
                      <p className="text-[10px] text-gray-500 uppercase tracking-[0.15em] font-bold mb-1">{n.label}</p>
                      <p className="text-xl font-black gradient-text">{n.value}</p>
                      <p className="text-[10px] text-gray-600">{n.unit}</p>
                    </div>
                  ))}
                </div>
              )}
              {dietPlan.timestamp && (
                <p className="text-[10px] text-gray-600 flex items-center gap-1.5"><Clock className="w-3 h-3" /> {new Date(dietPlan.timestamp).toLocaleString()} | {dietPlan.generation_time}s</p>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DietPlan;
