import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Activity, Loader2, AlertTriangle, Download, ArrowLeft } from 'lucide-react';
import { getSharedAssessment } from '../services/api';
import { ROUTES } from '../config/constants';

export default function SharedAssessment({ language }) {
  const { token } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const isTr = language === 'turkish';

  useEffect(() => {
    if (!token) return;
    (async () => {
      try {
        const result = await getSharedAssessment(token);
        setData(result);
      } catch (err) {
        setError(err.message || (isTr ? 'Değerlendirme bulunamadı.' : 'Assessment not found or link expired.'));
      } finally {
        setLoading(false);
      }
    })();
  }, [token, isTr]);

  const handlePrint = () => {
    if (!data) return;
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Assessment Report</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:20px;color:#333}
h1{color:#059669;border-bottom:2px solid #059669;padding-bottom:8px}
h2{color:#444;margin-top:24px}.badge{display:inline-block;padding:4px 12px;border-radius:8px;font-weight:bold;font-size:18px}
.high{background:#fee2e2;color:#dc2626}.moderate{background:#fef3c7;color:#d97706}
.low{background:#d1fae5;color:#059669}
.footer{margin-top:32px;padding-top:12px;border-top:1px solid #ddd;font-size:12px;color:#888}</style></head><body>
<h1>Diabetes Risk Assessment Report</h1>
<p><strong>Patient:</strong> ${data.user_name || 'N/A'}</p>
<p><strong>Date:</strong> ${data.created_at ? new Date(data.created_at).toLocaleString() : 'N/A'}</p>
<h2>Risk Level</h2>
<p><span class="badge ${(data.risk_level || '').toLowerCase().includes('high') ? 'high' : (data.risk_level || '').toLowerCase().includes('moderate') ? 'moderate' : 'low'}">${data.risk_level || 'Unknown'}</span></p>
<p><strong>Probability:</strong> ${data.probability != null ? (data.probability * 100).toFixed(1) + '%' : 'N/A'}</p>
<h2>Executive Summary</h2>
<p>${data.executive_summary || 'No summary available.'}</p>
<div class="footer"><p>Generated by Bonus Life AI Platform. This is not a medical diagnosis. Consult your healthcare provider.</p></div>
</body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const w = window.open(url, '_blank');
    if (w) w.onload = () => setTimeout(() => w.print(), 500);
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  };

  if (loading) {
    return (
      <div className="min-h-[70vh] flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-emerald-500" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-lg mx-auto px-6 py-32 text-center">
        <AlertTriangle className="w-12 h-12 text-red-400 mx-auto mb-4" />
        <h1 className="text-xl font-bold text-white mb-2">{isTr ? 'Değerlendirme Bulunamadı' : 'Assessment Not Found'}</h1>
        <p className="text-gray-400 text-sm mb-6">{error}</p>
        <Link to={ROUTES.HOME} className="inline-flex items-center gap-2 text-sm text-emerald-400 hover:text-emerald-300">
          <ArrowLeft className="w-4 h-4" /> {isTr ? 'Ana sayfaya dön' : 'Back to Home'}
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto px-6 py-32">
      <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.08]">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-emerald-500/10 flex items-center justify-center">
              <Activity className="w-5 h-5 text-emerald-400" />
            </div>
            <div>
              <h1 className="text-lg font-bold text-white">{isTr ? 'Paylaşılan Değerlendirme' : 'Shared Assessment'}</h1>
              <p className="text-xs text-gray-500">{isTr ? 'Hasta' : 'Patient'}: {data.user_name || 'N/A'}</p>
            </div>
          </div>
          <button onClick={handlePrint} className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm bg-white/[0.05] text-gray-400 hover:text-white border border-white/[0.08] transition">
            <Download className="w-4 h-4" /> PDF
          </button>
        </div>

        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06]">
              <p className="text-xs text-gray-500 mb-1">{isTr ? 'Risk Seviyesi' : 'Risk Level'}</p>
              <span className={`inline-block px-2 py-1 rounded text-sm font-bold
                ${(data.risk_level || '').includes('High') ? 'bg-red-500/20 text-red-400' : (data.risk_level || '').includes('Moderate') ? 'bg-amber-500/20 text-amber-400' : 'bg-emerald-500/20 text-emerald-400'}`}>
                {data.risk_level || 'Unknown'}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06]">
              <p className="text-xs text-gray-500 mb-1">{isTr ? 'Olasılık' : 'Probability'}</p>
              <p className="text-lg font-bold text-white">{data.probability != null ? `${(data.probability * 100).toFixed(1)}%` : 'N/A'}</p>
            </div>
          </div>

          {data.executive_summary && (
            <div>
              <p className="text-xs text-gray-500 mb-2">{isTr ? 'Özet' : 'Summary'}</p>
              <p className="text-sm text-gray-300 leading-relaxed">{data.executive_summary}</p>
            </div>
          )}

          {data.created_at && (
            <p className="text-xs text-gray-600">{isTr ? 'Tarih' : 'Date'}: {new Date(data.created_at).toLocaleString()}</p>
          )}

          <div className="pt-3 border-t border-white/[0.06]">
            <p className="text-[10px] text-gray-600">{isTr ? 'Bu bir tıbbi teşhis değildir. Sağlık hizmeti sağlayıcınıza danışın.' : 'This is not a medical diagnosis. Please consult your healthcare provider.'}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
